### ISSUE TITLE
More detailed documentation with more 'standard' usage of chunks?

### ISSUE THREAD

**Issue by DESIGNfromWITHIN** [Sterc/imagecropper#1]
I could just be missing something but the excample snippet code does not work for me.
Can this be used in a more 'traditional' way using a call like this?

`[[!ImageCropper? &image="social_media_image" &tpl="socialMediaImageTpl"]]`

**Comment by labr1005** [comment]
"image" needs to be the TV value, not just the name.
```
[[!ImageCropper?
    &image=`[[*social_media_image]]`
    &tpl=`socialMediaImageTpl`
]]
```
Take a look at the chunk "imageCropperImageTpl" (or core/components/imagecropper/elements/chunks/image.chunk.tpl) for how the placeholders are set.

You can also use [[+foo.width]] and [[+foo.height]] in your chunks.

**Comment by labr1005** [comment]
You can also set the placeholders [[+class]], [[+title]] and [[+alt]] in the snippet call:
```
[[!ImageCropper?
    &image=`[[*social_media_image]]`
    &tpl=`socialMediaImageTpl`
    &alt=`foo`
    &class=`bar`
    &title=`baz`
]]
```

**Comment by Oetzie** [comment]
Or you can use the snippet without a chunk to get the default/cropped imaged.

```
[[!ImageCropper?
    &image=`[[*social_media_image]]`
    &field=`desktop`
]]
```

The following snippet call will return the cropped image of the desktop, if there is no crop available it will return the default image.

I have updated the readme a little bit.
