### ISSUE TITLE
ImageCropper doesn't work nicely with pThumb

### ISSUE THREAD

**Issue by timluigjes** [Sterc/imagecropper#15]
When using ImageCropper with pThumb like in the example in README, the following error is thrown by pThumb that an image can't be found: 

`[pThumb] Resource: 1 \|\| Image: (none) File not found: public_html/  *** Skipping ***`

However the image is still showing on the website. Is there a way to use ImageCropper with pThumb as an fallback as described in the README?

**Comment by Oetzie** [comment]
```
{'!ImageCropper' | snippet : [
    'image'                 => $_pls['tv.overviewImage'],

    'tpl'                   => '@INLINE <div class="news-item__image"><img src="{$desktop.image ?: ($image | pThumb : "w=768&h=400&zc=1")}" /></div>',

    'usePdoTools'           => true
]}
```
