### ISSUE TITLE
Can this use an aspect ratio instead of exact values?

### ISSUE THREAD

**Issue by qodo** [Sterc/imagecropper#5]
Thank you for this - it looks incredible. I have only just started using this but wanted to ask if it is possible to make this use an aspect ratio instead of exact values. The reason for this is that I'd like to create approximate dimensions that are used in lots of places and this would just be used as a means of creating a focal point.

My JSON for this test was:

`{"square": {"name": "Square", "size": "1x1"}, "portrait": {"name": "Portrait", "size": "3x4"}, "landscape": {"name": "Landscape", "size": "4x3"}, "wide": {"name": "Wide", "size": "16x9"}}`

I would then like it to create images based on those ratios which I can then use. Is this possible? 

Using the config above it creates a 1x1px image instead of cropping the image to be a square around the cropped area I have drawn.

Thanks!

**Comment by Oetzie** [comment]
@qodo This is fixed in version 1.3.2 that will be released this week (currently testing this version). Instead of `{"size": "400x200"}` you need to set `{"proportion": "2x1"}`.

**Comment by qodo** [comment]
Thank you - this is awesome. Let me know if I can help with testing!

**Comment by Oetzie** [comment]
Fixed and released
