### ISSUE TITLE
Cannot use the ImageCropper snippet twice on a page

### ISSUE THREAD

**Issue by muzzwood** [Sterc/imagecropper#6]
Fantastic extra! Very impressed! :)

There's only one problem I've come across and that is that I can't use the "ImageCropper" snippet twice on a page.
The second snippet call returns the same value as the first snippet call. Even though both are uncached and the parameters are different.

Example JSON:
```
{"desktop": {"name": "Desktop", "size": "1920x400"}, "mobile": {"name": "Mobile", "size": "768x150"},"preview":{"name":"List Preview","size":"730x300"},"share":{"name":"Share","size":"1200x630"}}
```

First snippet call:
```
[[!ImageCropper? &image=`[[*crop_image]]` &field=`share`]]
```

Second snippet call:
```
[[!ImageCropper? &image=`[[*crop_image]]` &tpl=`crop_image_tpl` &alt=`[[*header_image_alt]]`]]
```

When I have both snippet calls on the page, both snippets output is `/assets/crops/hk-cf864cac9abd04be793b8010acca1826.jpg`
If I remove the first snippet call, the second one has the correct output from the "crop_image_tpl".

If I swap the order of the snippet calls around, then both give the same templated output of the new top one.

**Comment by muzzwood** [comment]
I found a workaround after some more experimenting.

Instead of using `&field` in the first snippet call:
```
[[!ImageCropper? &image=`[[*crop_image]]` &field=`share`]]
```
I switched to using an inline `&tpl` which contains the single field I'm after:
```
[[!ImageCropper? &image=`[[*crop_image]]` &tpl=`@INLINE [[+share.image]]`]]
```

Both snippet calls are now returning the expected output.

**Comment by Oetzie** [comment]
@digitalpenguin This is fixed in version 1.3.2 that will be released this week (currently testing this version).

**Comment by muzzwood** [comment]
Cheers, @Oetzie !

**Comment by Oetzie** [comment]
Fixed and released

**Comment by muzzwood** [comment]
Thanks, looks like it's working fine now!
